_wandb:
    value:
        cli_version: 0.18.0
        code_path: code/scripts/train_model.py
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": darwin-arm64
